/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")], // <-- Add this line
  content: [
    "./app/**/*.{js,tsx,ts,jsx}",
    // Add other directories if needed
  ],
  safelist: [
    "bg-green-700",
    "bg-white",
    "bg-transparent",
    "bg-[#f5f5f5]",
    "border-[1px]",
    "border-white",
    "border-gray-300",
    "border-t",
    "text-gray-700",
    "text-gray-600",
    "px-2",
    "px-3",
    "px-4",
    "py-2",
    "py-3",
    "py-4",
    "py-5",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "w-32",
    "w-1/3",
    "w-[28%]",
    "w-[30%]",
    "w-full",
    "h-full",
    "h-screen",
    "w-12",
    "h-12",
    "h-14",
    "h-16",
    "w-max",
    "item-center",
    "item-end",
    "justify-center",
    "justify-around",
    "justify-end",
    "flex-row",
    "gap-2",
    "mt-1",
    "mt-2",
    "mt-4",
    "mt-6",
    "mb-2",
    "mb-4",
    "mb-6",
    "text-lg",
    "text-xl",
    "text-left",
    "text-center",
    "text-right",
    "absolute",
    "fixed",
    "sticky",
    "bottom-0",
    "top-0",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
