name: Detect Existing PR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: 'The current branch the pr is been called'
        type: string
    outputs:
      skip_pr_creation:
        description: 'If PR creation needs to be skipped'
        value: ${{jobs.check-for-prs.outputs.skip_pr_creation}}
jobs:
  check-for-prs:
    runs-on: ubuntu-latest
    outputs:
      skip_pr_creation: ${{steps.pr-check.outputs.skip_pr_creation}}
    steps:
      - name: Check for existing PR
        id: pr-check
        run: |
          existing_pr=$(gh pr list --head ${{ inputs.branch }} --json number --jq '.[0].number')
          if [ -n "$existing_pr" ]; then
            echo "There is already an existing PR (#$existing_pr) for branch ${{ inputs.branch }}."
            echo "skipping PR creation and moving to checks, then auto-merge if checks pass."
            echo "skip_pr_creation=true" >> $GITHUB_OUTPUT
          else
            echo "There is no existing PR for branch ${{ inputs.branch }}."
            echo "skip_pr_creation=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
