name: Extract PR Metadata

on:
  workflow_call:
    inputs:
      branch:
        required: true
        description: 'The create branch the pr is to be created'
        type: string
    outputs:
      pr_number:
        description: 'This is the pull request number'
        value: ${{jobs.extract-pr-meta.outputs.pr_number}}
      pr_url:
        description: 'This is the url that points to the pull request'
        value: ${{jobs.extract-pr-meta.outputs.pr_url}}

jobs:
  extract-pr-meta:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{steps.get-pr.outputs.pr_number}}
      pr_url: ${{steps.get-pr.outputs.pr_url}}
    steps:
      - name: Get Pull Request Number
        id: get-pr
        run: |
          pr_number=$(gh pr list --head ${{ inputs.branch }} --json number --jq '.[0].number')
          pr_url=$(gh pr list --head ${{inputs.branch}} --json url --jq '.[0].url')
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
