name: Automate Pull Request

on:
  workflow_run:
    workflows: ['CodeQL Advanced']
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  get-branch-and-setup:
    runs-on: ubuntu-latest
    outputs:
      pr_branch: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - name: Extract branch name
        id: extract-branch
        run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Github CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
  detect-existing-pr:
    needs: [get-branch-and-setup]
    uses: ./.github/workflows/detect-pr.yml
    with:
      branch: ${{needs.get-branch-and-setup.outputs.pr_branch}}

  create-pull-request:
    needs: [get-branch-and-setup, detect-existing-pr]
    if: needs.detect-existing-pr.outputs.skip_pr_creation == 'false'
    uses: ./.github/workflows/create-pr.yml
    with:
      branch: ${{needs.get-branch-and-setup.outputs.pr_branch}}

  get-pr:
    needs: [get-branch-and-setup]
    uses: ./.github/workflows/extract-pr-metadata.yml
    with:
      branch: ${{needs.get-branch-and-setup.outputs.pr_branch}}

  pr-output:
    runs-on: ubuntu-latest
    needs: [get-pr, detect-existing-pr]
    outputs:
      pr_create_status: ${{steps.pr-creation-status.outputs.pr_creation_status}}
    steps:
      - name: Set Output On Success
        id: pr-creation-status
        if: success()
        run: echo "pr_creation_status=true" >> $GITHUB_OUTPUT

      - name: Log missing PR
        if: needs.get-pr.outputs.pr_number == '' && needs.detect-existing-pr.outputs.skip_pr_creation == 'true'
        run: echo "No pull request found — skipping checks and merge."

  add-pr-metadata:
    runs-on: ubuntu-latest
    needs: [pr-output, detect-existing-pr, get-pr]
    steps:
      - name: Add PR Metadata
        if: needs.pr-output.outputs.pr_create_status == 'true' || needs.detect-existing-pr.outputs.skip_pr_creation == 'true'
        uses: ./.github/workflows/add-pr-metadata.yml
        with:
          pr_url: ${{needs.get-pr.outputs.pr_url}}

  run-checks:
    needs: [get-pr]
    if: needs.get-pr.outputs.pr_number != ''
    uses: ./.github/workflows/checks.yml
    with:
      node-version: '20'

  auto-merge:
    runs-on: ubuntu-latest
    needs: [get-pr, run-checks]
    if: needs.run-checks.outputs.checks-passed == 'true' && needs.get-pr.outputs.pr_number != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-Merge the Pull Request
        uses: owen-6936/auto-merge-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ needs.get-pr.outputs.pr_number }}

  log-summary:
    runs-on: ubuntu-latest
    needs: [get-pr, run-checks, auto-merge]
    steps:
      - name: Log PR Summary
        run: |
          echo "🔗 PR URL: ${{ needs.get-pr.outputs.pr_url }}"
          echo "📦 PR Number: ${{ needs.get-pr.outputs.pr_number }}"
          echo "✅ Checks Passed: ${{ needs.run-checks.outputs.checks-passed }}"
          echo "🔀 Auto-Merged: ${{ needs.get-pr.outputs.pr_number != '' && needs.run-checks.outputs.checks-passed == 'true' }}"
