name: Automate Pull Request

on:
  workflow_run:
    workflows: ['CodeQL Advanced']
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_and_check_pr:
    runs-on: ubuntu-latest
    outputs:
      pr_branch: ${{ steps.extract-branch.outputs.branch }}
      pr_number: ${{ steps.get-pr.outputs.pr_number }}
      pr_url: ${{steps.get-pr.outputs.pr_url}}
      pr_create_status: ${{steps.pr-creation-status.outputs.pr_creation_status}}
      skip_pr_creation: ${{ steps.pr-check.outputs.skip_pr_creation }}
    steps:
      - name: Extract branch name
        id: extract-branch
        run: echo "branch=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Github CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Detect existing PR
        id: pr-check
        uses: ./.github/workflows/detect-pr.yml

      - name: Create Pull Request
        id: create-pr
        if: steps.pr-check.outputs.skip_pr_creation == 'false'
        uses: ./.github/workflows/create-pr.yml

      - name: Get Pull Request Number
        id: get-pr
        uses: ./.github/workflows/extract-pr-metadata.yml

      - name: Set Output On Success
        id: pr-creation-status
        if: success()
        run: echo "pr_creation_status=true" >> $GITHUB_OUTPUT

      - name: Log missing PR
        if: steps.get-pr.outputs.pr_number == '' && steps.pr-check.outputs.skip_pr_creation == 'true'
        run: echo "No pull request found — skipping checks and merge."

  add-pr-metadata:
    runs-on: ubuntu-latest
    needs: [create_and_check_pr]
    steps:
      - name: Add PR Metadata
        if: needs.create_and_check_pr.outputs.pr_create_status == 'true' || needs.create_and_check_pr.outputs.skip_pr_creation == 'true'
        uses: ./.github/workflows/add-pr-metadata.yml

  run-checks:
    runs-on: ubuntu-latest
    needs: [create_and_check_pr]
    outputs:
      checks-passed: ${{ steps.run-checks.outputs.checks-passed }}
    steps:
      - name: Run Checks Workflow
        if: needs.create_and_check_pr.outputs.pr_number != ''
        uses: ./.github/workflows/checks.yml
        with:
          node-version: '20'
        id: run-checks

  auto-merge:
    runs-on: ubuntu-latest
    needs: [create_and_check_pr, run-checks]
    if: needs.run-checks.outputs.checks-passed == 'true' && needs.create_and_check_pr.outputs.pr_number != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-Merge the Pull Request
        uses: owen-6936/auto-merge-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ needs.create_and_check_pr.outputs.pr_number }}
